site_name: AQW Python Bot
site_description: Documentation for the AQW automation toolkit.
site_url: https://example.com
repo_url: https://github.com/Froztt13/aqw-python
repo_name: Froztt13/aqw-python
nav:
  - Home: index.md
  - API:
      - Commands: api/commands.md
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            merge_init_into_class: true
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
watch:
  - core
  - model
  - docs

